name = "my-docusaurus-worker" # Replace with your desired Worker name
main = "src/index.js"        # <--- THIS IS YOUR WORKER'S JAVASCRIPT ENTRY POINT
compatibility_date = "2024-01-01" # Use a recent date for features

# No need for explicit [[kv_namespaces]] for assets if using [site]
# The [site] configuration automatically creates and manages a __STATIC_CONTENT KV namespace
# and uploads your static files to it.

[site]
bucket = "../path/to/your/docusaurus/build" # IMPORTANT: Adjust this path to your Docusaurus build directory
# entrypoint = "index.html" # <-- REMOVE THIS, it's not a valid field here