backend:
  name: github
  branch: main
  repo: BrandgrandRealMe/the-db
  base_url: https://db.brandgrand.rocks
  auth_endpoint: /api/auth
media_folder: "static/img"
public_folder: "/img"
collections:
  - name: "docs"
    label: "Docs"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }